### PR TITLE
update showpredictions() to use test image

### PR DESCRIPTION
**Pull request by lillythomas**

### CODE REVIEW

**Review by rbavery — APPROVED** [review]
woopisdaisy, thanks for catching this @lillythomas

**Comment by lillythomas** [comment]
@rbavery also I forgot to mention that mobilenetv2 likes to have input images (not masks) scaled to 0-1 and our input images are nominally 0-255. I added that back in to the augmentation pipeline in lesson 3. All you should have to do is add 

```
img = tf.cast(img, tf.float32) * (1/255.)
```

in `_augment()`

e.g. 

```
# Function to augment the images and labels
def _augment(img, label_img, img_size): 
  label_img = tf.image.resize(label_img, [224,224])
  img = tf.image.resize(img, [224,224])
  img = tf.cast(img, tf.float32) * (1/255.)
  aug_img = tf.numpy_function(func=aug_fn, inp=[img, img_size], Tout=tf.float32)
  return aug_img, label_img
```

**Comment by rbavery** [comment]
ah sounds good. merging @lillythomas

**Comment by lillythomas** [comment]
oh, and 

`sample_image = skio.imread(f'{img_dir}/tile_terrabio_17507.png') / 255.`

**Pull request merged**
