### PR TITLE
Lesson 4 evaluation and lesson 5 limited data progress

### PR DESCRIPTION
**Pull request by rbavery**

### CODE REVIEW

**Comment by rbavery** [comment]
@lillythomas the lesson 4 nb is ready for review. I've also made a few substantial updates to Lesson 3 to make it easier to load results in Lesson 4, as well as other small updates to Lesson 3.

**Comment by lillythomas** [comment]
@rbavery  as for Lesson 3 changes, I think we should keep `sample_image, sample_mask = batch_of_imgs[0], label[0,:,:,:]
` as is. It is defined and causes problems when running your new multi- prediction version where you've instead defined it as `image, mask = batch_of_imgs[0], label[0,:,:,:]
` because the `show_predictions()` expects `sample_image, sample_mask`.  When it is not defined as the original, then that show predictions function plots the same image every 27th `i` because it is using the `sample_image, sample_mask` defined in the above single image prediction. Does this make sense?

**Comment by rbavery** [comment]
Ah, I can update that so that the show predictions function doesn't use global vars which I think is the issue. If that sounds good I'll merge that this evening once I have wifi at the airport.

**Comment by lillythomas** [comment]
lgtm, merging

**Pull request merged**
